### ISSUE TITLE
Error 500 no RPI3B+

### ISSUE THREAD

**Issue by jeffersonpimenta** [weslleih/almoxarifado#2]
Olá,

Tentei instalar num RPI3B+ para testar e recebi o código 500 no navegador.

Meu apache é o 2.4.38, meu php é o 7.3 e mysql  15.1.

Alguma idéia de debug?

**Comment by weslleih** [comment]
Tem que olhar o erro na pasta de log do Apache

**Comment by jeffersonpimenta** [comment]
[Mon Sep 28 16:38:58.080205 2020] [php7:error] [pid 20099] [client 192.168.1.206:3299] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_pconnect() in /var/www/html/sistema/estoque/system/database/drivers/mysql/$
[Mon Sep 28 16:45:02.452774 2020] [mpm_prefork:notice] [pid 21459] AH00169: caught SIGTERM, shutting down
[Mon Sep 28 16:45:02.760192 2020] [mpm_prefork:notice] [pid 6301] AH00163: Apache/2.4.38 (Raspbian) configured -- resuming normal operations
[Mon Sep 28 16:45:02.760405 2020] [core:notice] [pid 6301] AH00094: Command line: '/usr/sbin/apache2'


Acho que é algo com o php e mysql. Há compatibilidade com o php 7?

**Comment by weslleih** [comment]
Fiz faz muito tempo, acho que a função que usei pra fazer a conexão com o banco está deprecated, não deve funcionar com php7 mesmo.

**Comment by jeffersonpimenta** [comment]
Alguma previsão pra atualizar ou algum rumo pra que eu possa fazer isso?

**Comment by weslleih** [comment]
Eu ando sem tempo para arrumar. O que precisa ser feito é atualizar o [CodeIgniter](https://codeigniter.com/), eu não usei nenhuma função muito complexa/específica dele, a atualização em tese deve ser simples.

**Comment by weslleih** [comment]
@jeffersonpimenta se ainda estiver precisando, da uma olhada na atualização que o @marceloalencar fez.

**Comment by jeffersonpimenta** [comment]
A versão dele tá dando ERR_CONNECTION_TIMED_OUT, verifiquei o BD e as configurações.

O apache tá dando o error

> PHP Startup: Unable to load dynamic library 'mysqli' (tried: /usr/lib/php/20180731/mysqli (/usr/lib/php/20180731/mysqli: cannot open shared object file: No such file or directory)

Creio que seja só besteira de configuração, assim que resolver posto a resolução aqui.

Att,

**Comment by marceloalencar** [comment]
Você precisa ter a extensão mysqli para PHP instalada.

**Comment by jeffersonpimenta** [comment]
Não acho que seja isso, tenho ela instalada e habilitada no php.ini, inclusive usando em outra aplicação no apache. Acho que deve ser algum detalhe de configuração da minha máquina, pois ela tá meio sambada de tanto mexer nas configurações...

**Comment by jeffersonpimenta** [comment]
Solução:

Descomentar a linha extension=mysqli no arquivo /etc/php/7.3/cli/php.ini e reiniciar o apache

Agradeço a ajuda!!
